name: colibri-dev

channels:
  - https://packages.nnpdf.science/public
  - conda-forge

dependencies:
  - nnpdf==4.0.6
  - mpi4py
  - pip
  - pip:
    - flake8
    - pytest
    - ultranest
    - flit
    - dill
    - jax
    - optax
    - flax
    