name: colibri-dev

channels:
  - https://packages.nnpdf.science/public
  - conda-forge

dependencies:
  - nnpdf
  - mpi4py
  - jax =0.4.13
  - optax =0.1.7
  - flax
  - pip
  - pip:
   - flake8
   - pytest
   - ultranest
   - flit