name: colibri-dev

channels:
  - conda-forge

dependencies:
  - python >= 3.11
  - mpich
  - lhapdf
  - pandoc
  - mpi4py
  - pip
  - pip:
    - -e .
    - colibri/models/wmin -e .
    - colibri/models/grid_pdf -e .
