dataset_inputs:
  - {'dataset':'NMC'}
  - {'dataset': 'SLACP_dwsh'}
  - {'dataset': 'SLACD_dw_ite'}
  - {'dataset': 'BCDMSP_dwsh'}
  - {'dataset': 'BCDMSD_dw_ite'}
  - {'dataset': 'CHORUSNUPb_dw_ite'}
  - {'dataset': 'CHORUSNBPb_dw_ite'}
  - {'dataset': 'NTVNUDMNFe_dw_ite', 'cfac': ['MAS']}
  - {'dataset': 'NTVNBDMNFe_dw_ite', 'cfac': ['MAS']}
  - {'dataset': 'HERACOMBNCEM'} 
  - {'dataset': 'HERACOMBNCEP575'}
  - {'dataset': 'HERACOMBNCEP820'}
  - {'dataset': 'HERACOMBNCEP920'}
  - {'dataset': 'HERACOMBNCEP460'}
  - {'dataset': 'HERACOMBCCEP'}
  - {'dataset': 'HERACOMBCCEM'} 
  - {'dataset':'HERACOMB_SIGMARED_B'}
  - {'dataset': 'HERACOMB_SIGMARED_C'}

positivity:
  posdatasets:
  - {dataset: POSF2U, maxlambda: 1e6}        # Positivity Lagrange Multiplier
  - {dataset: POSF2DW, maxlambda: 1e6}
  - {dataset: POSF2S, maxlambda: 1e6}
  - {dataset: POSFLL, maxlambda: 1e6}
  - {dataset: POSF2C, maxlambda: 1e6}
  - {dataset: POSXUQ, maxlambda: 1e6}        # Positivity of MSbar PDFs
  - {dataset: POSXUB, maxlambda: 1e6}
  - {dataset: POSXDQ, maxlambda: 1e6}
  - {dataset: POSXDB, maxlambda: 1e6}
  - {dataset: POSXSQ, maxlambda: 1e6}
  - {dataset: POSXSB, maxlambda: 1e6}
  - {dataset: POSXGL, maxlambda: 1e6}

  # - {dataset: POSDYU, maxlambda: 1e10}      # this is for hadronic data 
  # - {dataset: POSDYD, maxlambda: 1e10}
  # - {dataset: POSDYS, maxlambda: 1e10}

theoryid: 400

use_cuts: internal
use_t0: True

t0pdfset: NNPDF40_nnlo_as_01180
wminpdfset: NNPDF40_nnlo_as_01180 #210623_mnc_disonly_linear_1000
Q0: 1.65

patience: 15
max_epochs: 4000
learning_rate: 1e-4
optimizer: adam
n_replicas_wmin: 50
lambda_positivity: 100000 # 3000000
pos_test_size: 0.1

batch_size: 64
batch_seed: 1
pseudodata: true
# filterseed: 2

monte_carlo_replicas: 20

actions_:
  - snmc_fit
