name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CACHE_NUMBER: 0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: colibri-dev
          use-mamba: true

      - name: Cache Conda packages
        id: conda-pkgs
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}

      - name: Create env with matrix Python
        shell: bash -l {0}
        run: |
          mamba create -n colibri-dev "python=${{ matrix.python-version }}.*" -y

      - name: Update from environment.yml
        shell: bash -l {0}
        run: |
          mamba env update -n colibri-dev -f environment.yml --prune

      - name: Show versions
        shell: bash -l {0}
        run: |
          which python
          python -V
          conda list python | sed -n '1,6p'

      - name: Lint
        shell: bash -l {0}
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test
        shell: bash -l {0}
        run: |
          pip install pytest pytest-cov
          pytest -p no:warnings colibri/tests --cov=colibri --cov-report=xml --cov-config=.coveragerc

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.2.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}