name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CACHE_NUMBER: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: colibri-dev
          use-mamba: true
          auto-activate-base: false

      - name: Cache Conda packages
        id: conda-pkgs
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Create environment from environment.yml
        shell: bash -l {0}
        run: |
          mamba env create -n colibri-dev -f environment.yml

      - name: Lint
        shell: bash -l {0}
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test
        shell: bash -l {0}
        run: |
          pip install pytest pytest-cov
          pytest -p no:warnings colibri/tests --cov=colibri --cov-report=xml --cov-config=.coveragerc

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.2.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}